;;; core-autoload.el -- 一些常用的宏和函数. -*- lexical-binding: t; -*-
;;
;; Copyright (C) 2017-2022 kevin.scnu@gmail.com
;;
;; Author: Kevin Leung <kevin.scnu@gmail.com>
;; URL: https://github.com/lkzz/emacs.d
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3
;;
;;; Commentary:
;;
;;; Code:

(require 'autoload)

(defun my-generate-autoload-define (loaddef &rest DIRS)
  (let ((generated-autoload-file loaddef))
    (when (not (file-exists-p loaddef))
      (with-current-buffer (find-file-noselect generated-autoload-file)
	    (insert ";; generated by function: `my-generate-autoload-define'.")
	    (save-buffer)))
    (apply 'update-directory-autoloads DIRS)))

(defun my-reload-core-autoloads ()
  "Reload autoload function from `core/autoload' and save in `my-autoload-file'."
  (interactive)
  (when (file-exists-p my-autoload-file)
    (delete-file my-autoload-file t)
    (message "delete old autoload file: %s" my-autoload-file))

  (my-generate-autoload-define my-autoload-file (concat user-emacs-directory "core/autoload/"))
  (load my-autoload-file nil 'nomessage)
  (message "reload core autoload file: %s done." my-autoload-file))

(when (not (file-exists-p my-autoload-file))
  (my-generate-autoload-define my-autoload-file (concat user-emacs-directory "core/autoload/"))
  (byte-compile-file my-autoload-file)
  (message "generate autoload file: %s done." my-autoload-file))
(load my-autoload-file nil 'nomessage)

(provide 'core-autoload)
;;; core-autoload.el ends here
